-- SAMPLE DATA FOR CANDIDATE RANKING SYSTEM
-- Role: Recycling Production Line Manager

INSERT INTO candidates (name, experience_years, skills) VALUES
('Telly Carroll', 6, 'Team Leadership, Waste Recycling, Quality Control, Lean Manufacturing, Crisis Management'),
('Mr. Israel Rutherford', 9, 'Team Leadership, Lean Manufacturing, Process Optimization, Waste Recycling, Sustainability knowledge'),
('Bonita Cummerata', 3, 'Safety Compliance, Waste Recycling, Sustainability knowledge, Team Leadership'),
('Vincent Greenfelder', 11, 'Crisis Management, Sustainability knowledge, Process Optimization, Logistics Management, Team Leadership'),
('Eddie Blanda', 19, 'Crisis Management, Logistics Management, Safety Compliance, Process Optimization, Sustainability knowledge'),
('Margaretta Rolfson', 6, 'Logistics Management, Crisis Management, Sustainability knowledge'),
('Kim Schuppe', 10, 'Sustainability knowledge, Logistics Management, Team Leadership, Quality Control'),
('Blake Lubowitz', 19, 'Waste Recycling, Sustainability knowledge, Process Optimization, Safety Compliance'),
('Carter Halvorson', 6, 'Lean Manufacturing, Waste Recycling, Team Leadership'),
('Dr. Skyla Auer', 12, 'Crisis Management, Waste Recycling, Team Leadership, Sustainability knowledge, Quality Control'),
('Stewart Schumm', 12, 'Team Leadership, Waste Recycling, Process Optimization, Quality Control'),
('Erin Koch MD', 17, 'Waste Recycling, Quality Control, Crisis Management, Lean Manufacturing, Team Leadership'),
('Carolyn Homenick Sr.', 2, 'Crisis Management, Lean Manufacturing, Safety Compliance, Waste Recycling, Sustainability knowledge'),
('Jerry Kohler', 5, 'Quality Control, Lean Manufacturing, Team Leadership, Waste Recycling, Sustainability knowledge'),
('Antonio Stroman', 6, 'Waste Recycling, Process Optimization, Safety Compliance'),
('Earnest Labadie', 13, 'Safety Compliance, Team Leadership, Process Optimization, Crisis Management'),
('Janet Gusikowski', 17, 'Safety Compliance, Waste Recycling, Lean Manufacturing, Quality Control, Crisis Management'),
('Ervin Kunde', 8, 'Lean Manufacturing, Safety Compliance, Sustainability knowledge, Process Optimization'),
('Whitney Morissette', 19, 'Quality Control, Process Optimization, Team Leadership'),
('Vicki Schowalter', 12, 'Lean Manufacturing, Crisis Management, Logistics Management'),
('Jake Botsford', 6, 'Crisis Management, Safety Compliance, Waste Recycling, Lean Manufacturing'),
('Virginia Jones', 3, 'Quality Control, Waste Recycling, Lean Manufacturing'),
('Ena Rempel', 18, 'Logistics Management, Waste Recycling, Process Optimization'),
('Penny Morar Jr.', 2, 'Sustainability knowledge, Process Optimization, Safety Compliance'),
('Gregg Lebsack-Koepp', 8, 'Logistics Management, Safety Compliance, Crisis Management'),
('Lindsey Lang', 9, 'Process Optimization, Safety Compliance, Sustainability knowledge, Team Leadership, Lean Manufacturing'),
('Mrs. Amy Macejkovic', 15, 'Sustainability knowledge, Safety Compliance, Crisis Management, Process Optimization'),
('Nyah Price', 14, 'Sustainability knowledge, Lean Manufacturing, Waste Recycling'),
('Johnnie Glover', 5, 'Sustainability knowledge, Waste Recycling, Quality Control, Logistics Management, Process Optimization'),
('Dr. Alanna Heller', 6, 'Waste Recycling, Crisis Management, Process Optimization, Team Leadership, Logistics Management'),
('Pamela Schaefer V', 19, 'Team Leadership, Process Optimization, Safety Compliance, Quality Control'),
('Mrs. Brown O''Keefe IV', 14, 'Safety Compliance, Crisis Management, Process Optimization, Logistics Management'),
('Thelma Padberg', 5, 'Crisis Management, Sustainability knowledge, Safety Compliance, Waste Recycling, Process Optimization'),
('Allison Harvey', 19, 'Sustainability knowledge, Logistics Management, Crisis Management, Team Leadership, Process Optimization'),
('Mandy Volkman DDS', 3, 'Safety Compliance, Logistics Management, Crisis Management'),
('Jeannette Schultz', 7, 'Process Optimization, Quality Control, Team Leadership, Sustainability knowledge'),
('Ms. Richmond Lebsack III', 3, 'Lean Manufacturing, Team Leadership, Logistics Management, Process Optimization'),
('Maureen Toy', 6, 'Crisis Management, Quality Control, Logistics Management, Process Optimization'),
('Mrs. Jenifer Kutch', 14, 'Quality Control, Logistics Management, Sustainability knowledge'),
('Katie Vandervort', 19, 'Crisis Management, Quality Control, Logistics Management, Team Leadership');
